<a href="https://colab.research.google.com/github/Dawonlee0/LA2_Report/blob/main/%5B00%5D%EC%8B%A4%EC%8A%B5zero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world")

Hello world


라이브러리(패키지) 로드

In [ ]:
import numpy as np # np로 줄여서 쓰겠다

2. 벡터, 행열 연산, 그래프 그리기

In [ ]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:",x.shape)
  print("값:\n", x)
  print(" ")

In [ ]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 


In [ ]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 


In [ ]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 


In [ ]:
a = np.ones((3,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 


In [ ]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.1518726  0.53459452 0.06855069 0.02720556]
 [0.68931126 0.49102606 0.4340293  0.87210488]
 [0.38771763 0.20524073 0.23864868 0.134099  ]
 [0.43894215 0.60486093 0.83876584 0.55670911]]
 


In [ ]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[-0.3304999   1.16037627  0.74068727 -0.05562255]
 [ 1.56492567 -2.20826483 -0.0888164   0.00957791]
 [ 1.52847171 -0.54582493 -0.06506376 -1.10325393]
 [ 0.32610728  1.65963967 -0.52813246 -1.45877177]]
 
